### ISSUE TITLE
Failed to compile Assemblies couldn't be loaded

### ISSUE THREAD

**Issue by PawelStadnicki** [fable-compiler/repl#101]
I'm tryig to reuse Fable-Repl. However I got  "Failed to compile
Assemblies couldn't be loaded. Some firewalls prevent download of binary files, please check."
both locally and on Azure. 

Spent hours to figure out how this enable on firewall. 

How did you manage to solve it on the prod server?
Or it just worked without additional setup for you?

**Comment by alfonsogarciacaro** [comment]
Yes, it didn't require any additional setup. I just added the message because some users were reporting the calls to download the assemblies were failing and we concluded it was because of the firewall. But the error message is somewhat generic an the reason could be different in your case: https://github.com/fable-compiler/Fable/blob/972505785486fe003ab70764544c2cf498e32fcd/src/fable-standalone/src/Worker/Worker.fs#L91-L99

Also, please note the repl contains several "hacks" to make it work. Because of this, we don't provide specific support to run it in other environments (although some people have managed to do it). We did write a brief guide on how Fable could be run as a service in web app but it's not battle-tested. You can find it here: https://github.com/fable-compiler/Fable/issues/1651#issuecomment-463286299

**Comment by wrodemy** [comment]
Well indeed it seems be not related to firewall...
I quickly went throught steps from the comment and I have interesting finding.
I just deployed all my static files and depedencies/lib to Azure Storage, enabled Webpage option and it works! Real serverless :)

**Comment by PawelStadnicki** [comment]
I wanted to include my code in the REPL which points to my domain code (open wrometr.domain.addresses) but it obviously fails to find it.
I included reference to my domain code (github) in paket.depenedencies (first day when I use paket)
however when I do paket install or paket update to download it I have problems with Thoth-org and enums. It is slightly different when I do install or update but I assume the problem is the same - something has change in the Thoth 
I have no idea how to fix as I do not understand first why we have both Thoth.Json as nuget and github. I also did the update for both paket and npm so no futher ideas.

Second question : is this really all I have to do to use my domain code in REPL? Include the github url in paket.dependencies ? Need to update paket.references as well ? (how to do it when I use github reference, just point the files from paket-files?
