### ISSUE TITLE
Strange include path for .js file

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/repl#141]
This is how Sutil/WebComponents.fs imports webcomponent.js
```
[<Import("makeWebComponent", "./webcomponent.js")>]

```

However it produces a runtime error in the REPL with a strange import path, which I'm able to fix with a symbolic link. I'm wondering if the include path needs to be more REPL-friendly in some say?

The requested path is effectively "/src/Fable.Repl.Lib/Sutil/webcomponent.js"

For reference this is the patch to my deployment script (from Sutil's point of view which is hosting the repl at https://sutil.dev/repl"

```sh
mkdir ${TARGETDIR}/src
ln -s ${TARGETDIR}/../repl/js/repl/fable-repl-lib ${TARGETDIR}/src/Fable.Repl.Lib
```

**Comment by alfonsogarciacaro** [comment]
Yes, I had the same issue when including Sutil. This is because in Fable CLI the F# sources and potential JS files are kept in the same directory, but the REPL Lib is precompiled so we have to tell Fable to keep the import relative and **not** to use the original source. So two steps:

1. Add `${outPath}` in front of the import path to tell Fable to keep the import relative
2. Move the .js files to the output dir after Fable compilation

Example: https://github.com/fable-compiler/repl/blob/38e90b12be124be5db9cb4e897804e0ca066b71a/src/Fable.Repl.Lib/Sutil/Interop.fs#L40-L46

**Comment by davedawkins** [comment]
Great, thank you!
