### ISSUE TITLE
Broken in Safari

### ISSUE THREAD

**Issue by chkn** [fable-compiler/repl#162]
In Safari, the REPL never loads (clicking the Code tab shows the spinner indefinitely), and there is an error in the console:

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

**Comment by alfonsogarciacaro** [comment]
Oh, I recently made a change in a regex, not sure if related: https://github.com/fable-compiler/Fable/commit/0796241741e0d0baeb6ed70a253781e738acaa92#diff-f27c84517cce7ad7f5f496a09b678bc0449cbfd6ef079cd899d1dcb174557503

I could try adding the escape slash again (I removed it because I got a message in a Regex analyzer that it wasn't necessary but it was working before anyways), though I don't have a mac right now to test whether that was actually the problem. If you've a mac, can you please try the following code in Safari devtools to check if it raises an error?

```js
var r = /\{\{\s*\$(\d+)\s*\?\s*(.*?)\s*:\s*(.*?)\s*\}\}/
```

**Comment by stroborobo** [comment]
I tried looking into this issue, but failed at building the standalone lib because of the stack overflow issue with large lists, specifically FSStrings in this case.

Anyways, the RegEx you posted is working.

It's likely one with a lookbehind assertion, so containing either `?<=` or `?<!`. The negative one (second) can be found in some files like [sformat.fs][sformat.fs] or [Replacements.Util.fs][Replacements.Util.fs]. Not sure how important BabelPrinter.fs is, the other are Dart related.

[sformat.fs]: https://github.com/fable-compiler/Fable/blob/2a49b57/src/fcs-fable/src/Compiler/Utilities/sformat.fs#L1050
[Replacements.Util.fs]: https://github.com/fable-compiler/Fable/blob/main/src/Fable.Transforms/Replacements.Util.fs#L305

**Comment by JaggerJo** [comment]
#172

**Comment by MangelMaxime** [comment]
The latest version seems to be working for me in Safari, I will close this issue as this is a little old and the new version is just a few seconds old ^^.

Please feel free to open a new issue if needed
