### ISSUE TITLE
Fulma Dropdown does not compile

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fable-compiler/repl#90]
Selecting Fulma -> DropDown from https://fable.io/repl/ results in

`The namespace 'FontAwesome' is not defined.`

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro In order to support this example, we need to add `Fable.FontAwesome` support to the REPL. 

We also need to update Font Awesome deps to version 5.

Is adding `Fable.FontAwesome` to `Fable.Repl.Lib.fsproj` enough to add the new deps or we need to do something else too?

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @ImaginaryDevelopment, I've fixed the sample (and Fulma/Icon which was broken too). You may need to delete the storage cache for the website in order to update the sample code.

@MangelMaxime Unfortunately is a bit more contrived. First you need to make sure the code is compatible with the Repl Lib (sometimes [small changes are needed](https://github.com/fable-compiler/fable-recharts/commit/066ef0f71a6dced545c67792b6bd04f0a7da6ee9)) and then you also need to regenerate the metadata for Fable.Repl.Lib.dll using the `export` branch in ncave's FCS fork. With the update this has become a bit more complicated because now the Fable.Repl.Lib assembly is coming from the fable-metadata package, but I need to make it possible again to regenerate the .dll directly from this repo.

Maybe we can add the Fable.FontAwesome dependency later (although I'd try to keep dependencies to a minimum as they affect the REPL startup time), but for now I just fixed the samples using the class names directly :)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ok no problem and thank you for fixing it :)
