### ISSUE TITLE
Fails to use Thoth.Json.Decode.Auto on record type

### ISSUE THREAD

**Issue by kqr** [fable-compiler/repl#97]
I tried the attached snippet at https://fable.io/repl and it failed with the following error:

> Error: Cannot generate auto decoder for Test.ARecord. Please pass an extra decoder.

I *think* I understand when extra decoders are needed, and, crucially, when they should not be needed, which is the case here. This should be a plain record type with a simple member, which is something Thoth.Json should be able to automatically derive a decoder for.

Why does this code fail in the REPL? Is this a sign of a more serious issue in the Fable compiler?

```
open Browser
open Thoth.Json

type ARecord = { Anumber : int }

let main =
    let u = Decode.Auto.fromString<ARecord>("""{  "anumber": 7 }""")
    console.log(u)
```

**Comment by kqr** [comment]
To be clear: I have not ruled out that I might simply have missed something obvious and embarrassing. Please tell me if that is the case!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I tried to update the Fable libs (Thoth.Json, etc.) to the latest version but still have the error.

I don't really know why do have it as according to the generated JS Fable do output the reflection info.

**Comment by alfonsogarciacaro** [comment]
@kqr This is working with fable-compiler so hopefully is not a problem with Fable :) Fable doesn't include reflection information in the objects by default to minimize the generated code size, but this means when reflection is used (as in Thoth.Json.Decode.Auto) a bit of magic from the compiler is needed. This "magic" works a bit differently in the REPL because of its limitations.

In principle I'd say Thoth.Json.Decode.Auto should work but obviously it doesn't. I cannot tell right now what's the problem but I'll try to check it. Thanks for reporting!

**Comment by MangelMaxime** [comment]
I think I know where the problem is coming from.

The libraries like Thoth.Json are importing their dependencies from `"../fable-library.2.4.14/Reflection.js"` while the code generated by the REPL is using `fable-library/Reflection.js`.

I suspect that even if we build the REPL and libs using the same version of fable, for the browser the object instance are not the same when comparing then using `instanceof`.

**Comment by MangelMaxime** [comment]
Ok, I confirm this is the problem.

If I force the REPL generated code to use files from `/js/repl/lib/fable-library.2.4.14` then it's working
